<div id="site-menu">
    <nav>
        <ul>
            <li class="menu-li">
                <p class="menu-li-title">Meny</p>
            </li>
            <li>
                <a href="dashboard.php" id="home-btn">Hem</a>
            </li>
            <li>
                <a href="dashboard_subscription.php" id="subscription-btn">Prenumerera</a>
            </li>
            <li>
                <a href="dashboard_send_script.php" id="send-script-btn">Skicka manus</a>
            </li>
            <li>
                <a href="dashboard_about.php" id="about-btn">Om TGV</a>
            </li>
            <li>
                <a href="dashboard_contact.php" id="contact-btn">Kontakt & Footer</a>
            </li>
            <li>
                <a href="logout.php" id="logout-btn">Logga ut</a>
            </li>
        </ul>
    </nav>
</div>