<footer>
    <div class="footer-block-about">
        <h2 class="footer-title">Om TGV</h2>
        <p>Tidskrift för genusvetenskap är det nya namnet på tidigare Kvinnovetenskaplig tidskrift, som startades 1980 i Lund. TGV är Nordens största referee-granskade tidskrift för aktuell tvärvetenskaplig genusforskning. </p>
    </div>
    <div class="footer-block">
        <h2 class="footer-title">Site map</h2>
        <p><a href="../about.php">Om TGV</a></p>
        <p><a href="../subscription.php">Prenumerera</a></p>
        <p><a href="http://ojs.ub.gu.se/ojs/index.php/tgv">Tidigare nummer</a></p>
        <p><a href="../send_script.php">Skicka manus</a></p>
    </div>
    <div class="footer-block">
        <h2 class="footer-title">Kontakt</h2>
        <p>054-7001000</p>
        <p>tegeve@oru.se</p>
        <p>Universitetsgatan 2</p>
        <p>651 88 Karlstad</p>
    </div>
</footer> 