<nav id="nav_mobile">
        <a id="menyButton">Meny</a>
        <ul id="mobile_ul">
                <li>
                    <a href="/">Hem</a>
                </li>
                <li>
                    <a href="subscription.php">Prenumerera</a>
                </li>
                <li>
                    <a href="old_articles.php">Tidigare nummer</a>
                </li>
                <li>
                    <a href="send_script.php">Skicka manus</a>
                </li>
                <li>
                    <a href="about.php">Om TGV</a>
                </li>
                <li>
                    <a href="contact.php">Kontakt</a>
                </li>
        </ul>
</nav> 