<!--<a href="#" id="menu-toggle">MENY</a>
<nav>
    <div id="menu-slidedown">
        <ul>
            <li>
                <a href="index.php">Hem</a>
            </li>
            <li>
                <a href="subscription.php">Prenumerera</a>
            </li>
            <li>
                <a href="http://ojs.ub.gu.se/ojs/index.php/tgv" target="_blank">Tidigare nummer</a>
            </li>
            <li>
                <a href="send_script.php">Skicka manus</a>
            </li>
            <li>
                <a href="about.php">Om TGV</a>
            </li>
            <li>
                <a href="contact.php">Kontakt</a>
            </li>
        </ul>
    </div>
</nav>-->
<nav id="nav-hide">
    <ul>
        <li>
            <a href="index.php">Hem</a>
        </li>
        <li>
            <a href="subscription.php">Prenumerera</a>
        </li>
        <li>
            <a href="http://ojs.ub.gu.se/ojs/index.php/tgv" target="_blank">Tidigare nummer</a>
        </li>
        <li>
            <a href="send_script.php">Skicka manus</a>
        </li>
        <li>
            <a href="about.php">Om TGV</a>
        </li>
        <li>
            <a href="contact.php">Kontakt</a>
        </li>
    </ul>
</nav>
<a href="#" id="menu-toggle" class="menu-toggle-hide">MENY</a>
<nav class="fixed-2" id="nav-hide-mobile">
    <div id="menu-slidedown">
        <ul>
            <li>
                <a href="index.php">Hem</a>
            </li>
            <li>
                <a href="subscription.php">Prenumerera</a>
            </li>
            <li>
                <a href="http://ojs.ub.gu.se/ojs/index.php/tgv" target="_blank">Tidigare nummer</a>
            </li>
            <li>
                <a href="send_script.php">Skicka manus</a>
            </li>
            <li>
                <a href="about.php">Om TGV</a>
            </li>
            <li>
                <a href="contact.php">Kontakt</a>
            </li>
        </ul>
    </div>
</nav>