<nav>
    <ul>
        <li>
            <a href="index.php">Hem</a>
        </li>
        <li>
            <a href="subscription.php">Prenumerera</a>
        </li>
        <li>
            <a href="http://ojs.ub.gu.se/ojs/index.php/tgv" target="_blank">Tidigare nummer</a>
        </li>
        <li>
            <a href="send_script.php">Skicka manus</a>
        </li>
        <li>
            <a href="about.php">Om oss</a>
        </li>
        <li>
            <a href="contact.php">Kontakt</a>
        </li>
    </ul>
</nav>